language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

install:
  - travis_retry sudo apt-get install parallel

before_script:
  - phpenv rehash
  - mysql -e 'create database www_tests_symfony;'
  - mysql -e 'create database www_tests_phpbb;'
  - cp app/config/parameters_travis.yml app/config/parameters.yml
  - travis_retry php composer.phar install -v --dev

script:
  - bin/phpunit -c app/
  - travis_retry bin/security-checker security:check composer.lock
  - find . -path ./vendor -prune -o -type f -name "*.php" | parallel --gnu --keep-order 'php -l {} > /dev/null' || exit 1
  - php app/console twig:lint @AppBundle

notifications:
  email:
    recipients:
      - website@phpbb.com
    on_success: change
    on_failure: change
