parameters:
    # Shouldn't need to touch this
    database_driver:        pdo_mysql
    phpbb_database_driver:  pdo_mysql
    database_host:          localhost
    phpbb_database_host:    localhost
    database_port:          ~
    phpbb_database_port:    ~

    # This DB should NOT EXIST. The user listed should have access to create dbs and have full access to those dbs.
    # This is the DB for Symfony
    database_name:      phpbb_symfony
    database_user:      root
    database_password:  ~

    # This should be about the install of the phpbb database for the website, likely at phpbb.local/community/
    phpbb_database_name:        phpbb_local
    phpbb_database_user:        root
    phpbb_database_password:    ~
    phpbb_database_prefix:      c_

    # Databases for testing. These databases should exist
    # The users should have full access to the databases and access to create/destroy databases.
    test_database_driver:            pdo_mysql
    phpbb_test_database_driver:      pdo_mysql
    test_database_host:              localhost
    phpbb_test_database_host:        localhost
    test_database_port:              ~
    phpbb_test_database_port:        ~
    test_database_name:              phpbb_test_symfony
    test_database_user:              root
    test_database_password:          ~
    phpbb_test_database_name:        phpbb_test_local
    phpbb_test_database_user:        root
    phpbb_test_database_password:    ~

    # Mailer Settings, shouldn't need to touch these unless its a live install.
    mailer_transport:   mail
    mailer_host:        ~
    mailer_user:        ~
    mailer_password:    ~
    mailer_port:        ~
    mailer_encryption:  ~
    mailer_auth_mode:   ~
    mailer_delivery_address:   ~
    mailer_disable_delivery:   true

    locale:             en

    # Change this to something random (just hit random keys on your keyboard if you must)
    secret:             ThisTokenIsNotThatSecretChangeItOnAllInstallations

    # See services.yml for options
    cacheDriver:        phpbb.filesystem_cache
    # memcached or array
    ormCache:           array
    # localhost or ~
    ormCacheHost:       ~
    # 11211 or ~
    ormCachePort:       ~
    # Memcached or ~
    ormCacheInstanceClass: ~

    # Location should be local or live
    location:           local

    # Ignore this.
    java_location:      /usr/bin/java
