phpBBWebsite_Mods_home:
    path:  /
    defaults:
        _controller: PhpbbWebsiteInterfaceBundle:StaticTemplate:staticTemplate
        template: PhpbbWebsiteInterfaceBundle:Mods:home.html.twig
    methods:  [GET]
