phpBBWebsite_Support_home:
    path:  /
    defaults:
        _controller: PhpbbWebsiteInterfaceBundle:StaticTemplate:staticTemplate
        template: PhpbbWebsiteInterfaceBundle:Support:home.html.twig
    methods:  [GET]

phpBBWebsite_Support_irc:
    path:  /irc/
    defaults:
        _controller: PhpbbWebsiteInterfaceBundle:StaticTemplate:staticTemplate
        template: PhpbbWebsiteInterfaceBundle:Support:irc.html.twig
    methods:  [GET]
