phpBBWebsite_Support_home:
    path:  /
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Support:home.html.twig
    methods:  [GET]

phpBBWebsite_Support_irc:
    path:  /irc/
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Support:irc.html.twig
    methods:  [GET]

phpBBWebsite_Support_intl:
    path:  /intl/
    defaults:
        _controller: AppBundle:StaticTemplate:staticTemplate
        template: AppBundle:Support:intl.html.twig
    methods:  [GET]
