Phpbb\WebsiteInterfaceBundle\Entity\EpvResults:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        github:
            type: string
            length: 255
        runtime:
            type: integer
    lifecycleCallbacks: {  }
