PhpbbPrivateWebsiteBundle_cache_clear:
    path: /tools/cache/clear/{password}/
    defaults: { _controller: PhpbbPrivateWebsiteBundle:ManagementTools:cacheClear }

PhpbbPrivateWebsiteBundle_cache_warmup:
    path: /tools/cache/warmup/{password}/
    defaults: { _controller: PhpbbPrivateWebsiteBundle:ManagementTools:cacheWarmup }
