parameters:
#    php_bb_private_website.example.class: phpBB\PrivateWebsiteBundle\Example

services:
#    php_bb_private_website.example:
#        class: %php_bb_private_website.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

	# phpbb.twig.privateglobalvars:
	# 	class: phpBB\PrivateWebsiteBundle\Twig\PrivateGlobalsExtension
	# 	tags:
	# 		- { name: twig.extension }
