parameters:
#    phpbb_website_interface.example.class: Phpbb\WebsiteInterfaceBundle\Example

services:
#    phpbb_website_interface.example:
#        class: %phpbb_website_interface.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    phpbb.twig.globalvars:
        class: Phpbb\WebsiteInterfaceBundle\Twig\GlobalsExtension
        tags:
            - { name: twig.extension }

    phpbb.memcached:
        class: memcached
        calls:
            - [ addServer, ['localhost', 11211] ]

    phpbb.apc_cache:
        class: Doctrine\Common\Cache\ApcCache

    phpbb.array_cache:
        class: Doctrine\Common\Cache\ArrayCache

    phpbb.filesystem_cache_factory:
        class: Phpbb\WebsiteInterfaceBundle\Factory\FilesystemCacheFactory
        arguments: [ @kernel ]

    phpbb.filesystem_cache:
        class: Doctrine\Common\Cache\FilesystemCache
        factory_service: phpbb.filesystem_cache_factory
        factory_method: get

    phpbb.memcached_cache:
        class: Doctrine\Common\Cache\MemcachedCache
        calls:
            - [ setMemcached, [@phpbb.memcached] ]

    phpbb.cacheFactory:
        class: Phpbb\WebsiteInterfaceBundle\Factory\CacheFactory
        arguments: [ @service_container, %cacheDriver% ]

    phpbb.cache:
        class: Phpbb\WebsiteInterfaceBundle\Factory\CacheFactory
        factory_service: phpbb.cacheFactory
        factory_method: get

    phpbb.downloadManager:
        class: Phpbb\WebsiteInterfaceBundle\Utilities\downloadManager
        arguments: [ @phpbb.cache, @kernel ]
